"""Add stock_actual and cantidad_requerida

Revision ID: 194ea7ae7ae2
Revises: fb49b5c3a61d
Create Date: 2026-05-24 21:41:48.470501
"""

from alembic import op
import sqlalchemy as sa



revision = '194ea7ae7ae2'
down_revision = 'fb49b5c3a61d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredientes', sa.Column('stock_actual', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('producto_ingrediente', sa.Column('cantidad_requerida', sa.Numeric(precision=10, scale=2), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producto_ingrediente', 'cantidad_requerida')
    op.drop_column('ingredientes', 'stock_actual')
    # ### end Alembic commands ###
