"""Update_ingredientes_y_recetas

Revision ID: 75f2196c70df
Revises: 20260528_0003
Create Date: 2026-06-15 14:28:21.177865
"""

from alembic import op
import sqlalchemy as sa



revision = '75f2196c70df'
down_revision = '20260528_0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredientes', sa.Column('stock_cantidad', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False))
    # We might not have a unidad_medida with id=1, but we need a dummy value to alter column to NOT NULL if rows exist. 
    # If it fails, the user needs to ensure at least one unidad_medida exists. Let's assume ID 1 exists.
    op.add_column('ingredientes', sa.Column('unidad_medida_id', sa.Integer(), server_default='1', nullable=False))
    op.create_foreign_key(None, 'ingredientes', 'unidades_medida', ['unidad_medida_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('ingredientes', 'stock_actual')
    op.drop_column('ingredientes', 'unidad')
    op.add_column('producto_ingrediente', sa.Column('cantidad', sa.Numeric(precision=10, scale=2), server_default='1', nullable=False))
    op.add_column('producto_ingrediente', sa.Column('unidad_medida_id', sa.Integer(), server_default='1', nullable=False))
    op.create_foreign_key(None, 'producto_ingrediente', 'unidades_medida', ['unidad_medida_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('producto_ingrediente', 'cantidad_requerida')
    op.drop_constraint(op.f('productos_unidad_venta_id_fkey'), 'productos', type_='foreignkey')
    op.create_foreign_key(None, 'productos', 'unidades_medida', ['unidad_venta_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productos', type_='foreignkey')
    op.create_foreign_key(op.f('productos_unidad_venta_id_fkey'), 'productos', 'unidades_medida', ['unidad_venta_id'], ['id'], ondelete='SET NULL')
    op.add_column('producto_ingrediente', sa.Column('cantidad_requerida', sa.NUMERIC(precision=10, scale=2), server_default=sa.text("'1'::numeric"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'producto_ingrediente', type_='foreignkey')
    op.drop_column('producto_ingrediente', 'unidad_medida_id')
    op.drop_column('producto_ingrediente', 'cantidad')
    op.add_column('ingredientes', sa.Column('unidad', sa.VARCHAR(length=20), server_default=sa.text("'unidad'::character varying"), autoincrement=False, nullable=False))
    op.add_column('ingredientes', sa.Column('stock_actual', sa.NUMERIC(precision=10, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ingredientes', type_='foreignkey')
    op.drop_column('ingredientes', 'unidad_medida_id')
    op.drop_column('ingredientes', 'stock_cantidad')
    # ### end Alembic commands ###
