"""Add soft delete

Revision ID: fb49b5c3a61d
Revises: 20260524_0001
Create Date: 2026-05-24 21:17:04.363588
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = 'fb49b5c3a61d'
down_revision = '20260524_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estados_pedido', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('roles', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('usuario_roles', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario_roles', 'deleted_at')
    op.drop_column('roles', 'deleted_at')
    op.drop_column('estados_pedido', 'deleted_at')
    # ### end Alembic commands ###

